# --- !Ups
CREATE TABLE PARTIAL_POLL_CHOICES(ID SERIAL PRIMARY KEY, NAME VARCHAR(1000) NOT NULL, UNIVERSAL_VALUE VARCHAR(1000), PARTIAL_POLL_ID INTEGER NOT NULL, VALUE FLOAT4 DEFAULT 0);

CREATE TABLE POLLS(ID SERIAL PRIMARY KEY, TOPIC VARCHAR(1000), EXPIRATION_DATE DATE, REMOTE_IDENTIFIER VARCHAR(1000), LOCATION VARCHAR(1000), CREATED_DATE DATE, IS_ACTIVE CHAR(1) DEFAULT 'N');

CREATE TABLE PARTIAL_POLLS(ID SERIAL PRIMARY KEY, POLL_ID INTEGER NOT NULL, POLLSTER VARCHAR(1000), PROVIDER VARCHAR(1000), IS_ACTIVE CHAR(1) DEFAULT 'N');

# --- !Downs
DROP TABLE POLLS;

DROP TABLE PARTIAL_POLLS;

DROP TABLE PARTIAL_POLL_CHOICES;