# --- !Ups
CREATE TABLE PARTIAL_POLL_CHOICES(ID SERIAL PRIMARY KEY, NAME VARCHAR(1000) NOT NULL, UNIVERSAL_VALUE VARCHAR(1000), PARTIAL_POLL_ID INTEGER NOT NULL);

CREATE TABLE POLLS(ID SERIAL PRIMARY KEY, TOPIC VARCHAR(1000), EXPIRATION_DATE DATE, REMOTE_IDENTIFIER VARCHAR(1000));

CREATE TABLE PARTIAL_POLLS(ID SERIAL PRIMARY KEY, POLL_ID INTEGER NOT NULL, POLLSTER VARCHAR(1000), PROVIDER VARCHAR(1000));

# --- !Downs
DROP TABLE POLLS;

DROP TABLE PARTIAL_POLLS;

DROP TABLE PARTIAL_POLL_CHOICES;