# --- !Ups
CREATE TABLE POLL_CHOICES(ID SERIAL PRIMARY KEY, NAME VARCHAR(1000) NOT NULL);

CREATE TABLE POLLERS(ID SERIAL PRIMARY KEY, NAME VARCHAR(1000) NOT NULL);

CREATE TABLE PARTIAL_POLL_CHOICES(ID SERIAL PRIMARY KEY, NAME VARCHAR(1000) NOT NULL, POLL_CHOICE_ID INTEGER NOT NULL, PARTIAL_POLL_ID INTEGER NOT NULL);

CREATE TABLE POLLS(ID SERIAL PRIMARY KEY, TOPIC VARCHAR(1000), EXPIRATION_DATE DATE);

CREATE TABLE PARTIAL_POLLS(ID SERIAL PRIMARY KEY, POLLER_ID INTEGER NOT NULL, POLL_ID INTEGER NOT NULL);

# --- !Downs
DROP TABLE POLLS;

DROP TABLE PARTIAL_POLLS;

DROP TABLE PARTIAL_POLL_CHOICES;

DROP TABLE POLLERS;

DROP TABLE POLL_CHOICES;