# --- !Ups
CREATE SEQUENCE POLL_SEQ INCREMENT BY 1 START WITH 1;

CREATE SEQUENCE PARTIAL_POLL_SEQ INCREMENT BY 1 START WITH 1;

CREATE SEQUENCE PARTIAL_CHOICE_SEQ INCREMENT BY 1 START WITH 1;

# --- !Downs
DROP SEQUENCE POLL_SEQ;
DROP SEQUENCE PARTIAL_POLL_SEQ;
DROP SEQUENCE PARTIAL_CHOICE_SEQ;