# --- !Ups
CREATE SEQUENCE POLL_SEQ INCREMENT BY 1 START WITH 1;

CREATE SEQUENCE POLLER_SEQ INCREMENT BY 1 START WITH 1;

CREATE SEQUENCE PARTIAL_POLL_SEQ INCREMENT BY 1 START WITH 1;

CREATE SEQUENCE POLL_CHOICE_SEQ INCREMENT BY 1 START WITH 1;

CREATE SEQUENCE POLLER_CHOICE_SEQ INCREMENT BY 1 START WITH 1;

# --- !Downs
DROP SEQUENCE POLL_SEQ;
DROP SEQUENCE POLLER_SEQ;
DROP SEQUENCE PARTIAL_POLL_SEQ;
DROP SEQUENCE POLL_CHOICE_SEQ;
DROP SEQUENCE POLLER_CHOICE_SEQ;